### ISSUE TITLE
Latex issues and additional courses

### ISSUE THREAD

**Issue by thesimonho** [JohnGiorgi/deeplearning.ai-coursera-notes#1]
Just wondering if you're planning on adding notes for the CNN and hyperparameter tuning courses?

Also, some of the latex is not rendering correctly on the compiled html page (e.g. see the sequence model sections)

**Comment by JohnGiorgi** [comment]
Hi! Thanks for pointing them out. I think I fixed most of them -- I'll do another pass and clean stuff up when I get some time.

I do plan on taking the remaining two courses, unfortunately, I don't have a lot of free time as of late -- might not get to these until the spring.
