### ISSUE TITLE
Missing image(s)

### ISSUE THREAD

**Issue by thesimonho** [JohnGiorgi/deeplearning.ai-coursera-notes#3]
There appears to be a broken image link in week 2 of course 3:
https://johngiorgi.github.io/deeplearning.ai-coursera-notes/structuring_machine_learning_projects/week_2/#more-general-formation

Image url:
https://s19.postimg.org/bfl8ak6xv/Screen_Shot_2018-02-25_at_4.34.00_PM.png

More generally, are you planning on uploading the images to github and using local links (as with some of your other course notes)? I had started downloading the images just in case the links die or the host disappears some time in the future, but looks like some of the image links are already not working

If you want, I can change the urls over and make a pull request with the updated files as I'm slowly making my way through these courses anyway. I'd just need your local copies of the images pushed up to the repo

**Comment by JohnGiorgi** [comment]
Thanks for pointing that out! I fixed all the broken image links in week 2 of course 3.

> More generally, are you planning on uploading the images to github and using local links (as with some of your other course notes)? I had started downloading the images just in case the links die or the host disappears some time in the future, but looks like some of the image links are already not working

I wish I did this in the first place for this course. Alas.

> If you want, I can change the urls over and make a pull request with the updated files as I'm slowly making my way through these courses anyway. I'd just need your local copies of the images pushed up to the repo

I don't actually have local copies anymore 👎 So this would involve downloading them all from the image hosting site, uploading to GitHub and changing over the URLs - probably more work then it is worth. 

Although, if you still want to do it, the images are hosted [here](https://postimg.cc/gallery/32c29uphc/)!

Thanks again.
